Execute: DrawSystematicUncertainties.cpp
	g++ DrawSystematicUncertainties.cpp -o Execute \
		`root-config --glibs --cflags` \
		-I$(ProjectBase)/CommonCode/include \
		$(ProjectBase)/CommonCode/library/*.o