ExecutePlotBinningSyst: plotBinningSyst.cpp
	g++ plotBinningSyst.cpp -o ExecutePlotBinningSyst \
		`root-config --libs --cflags` \
		-I$(ProjectBase)/CommonCode/include \
		$(ProjectBase)/CommonCode/library/*.o